Transform: AWS::Serverless-2016-10-31

Resources:
  SendSmsLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/send-sms.handler
      Runtime: nodejs14.x
      Tracing: Active
      MemorySize: 128
      Timeout: 10
      #      FunctionUrlConfig:
      #        AuthType: NONE
      #        Cors:
      #          AllowOrigins:
      #            - "https://example.com"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: '*'

  SendSmsLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SendSmsLambda}
      RetentionInDays: 180

  SendSmsLambdaUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref SendSmsLambda
      AuthType: NONE
      Cors:
        AllowOrigins:
          - '*'
        AllowMethods:
          - POST
        AllowHeaders:
          - Content-Type
          - Content-Length
          - Accept-Encoding
          - Connection
          - User-Agent
        ExposeHeaders:
          - Content-Type
          - Content-Length
          - Content-Encoding
          - Connection
          - Date
        MaxAge: 300
        AllowCredentials: false

  SendSmsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SendSmsLambda
      Principal: '*'
      Action: lambda:InvokeFunctionUrl
      FunctionUrlAuthType: NONE

Outputs:
  APIEndpoint:
    Description: "Lambda URL"
    Value: !GetAtt SendSmsLambdaUrl.FunctionUrl
